[package]
name = "blue_git"
description = "Git related utilities for Blue"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
